<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>local.prototype</groupId>
  <artifactId>gumtree-cli-runtime</artifactId>
  <version>0.1.0</version>

  <dependencies>
    <dependency>
      <groupId>com.github.gumtreediff</groupId>
      <artifactId>client.diff</artifactId>
      <version>4.0.0-beta7</version>
    </dependency>
    <dependency>
      <groupId>com.github.gumtreediff</groupId>
      <artifactId>gen.treesitter-ng</artifactId>
      <version>4.0.0-beta7</version>
    </dependency>
  </dependencies>
</project>
